issue with ip-filter finally averted
basically reverted the changes needed for SWIG after the wrappers are generated and before compilation so that it will build as intented by the original code.

Onto the next issue, probably a file that moved or no longer exists

libtorrent_jni.cpp:885:10: fatal error: 'libtorrent/tracker_event.hpp' file not found
#include <libtorrent/tracker_event.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~